/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyPostsRouteImport } from './routes/my-posts'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorsIdRouteImport } from './routes/tutors/$id'
import { Route as RequirementsIdRouteImport } from './routes/requirements/$id'
import { Route as ProfilesIdRouteImport } from './routes/profiles/$id'
import { Route as OnboardingTutorRouteImport } from './routes/onboarding/tutor'
import { Route as OnboardingStudentRouteImport } from './routes/onboarding/student'
import { Route as BidsIdRouteImport } from './routes/bids/$id'
import { Route as AuthRoleRouteImport } from './routes/auth/role'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPostsRoute = MyPostsRouteImport.update({
  id: '/my-posts',
  path: '/my-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsIdRoute = TutorsIdRouteImport.update({
  id: '/tutors/$id',
  path: '/tutors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsIdRoute = RequirementsIdRouteImport.update({
  id: '/requirements/$id',
  path: '/requirements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdRoute = ProfilesIdRouteImport.update({
  id: '/profiles/$id',
  path: '/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTutorRoute = OnboardingTutorRouteImport.update({
  id: '/onboarding/tutor',
  path: '/onboarding/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStudentRoute = OnboardingStudentRouteImport.update({
  id: '/onboarding/student',
  path: '/onboarding/student',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsIdRoute = BidsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BidsRoute,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/auth/role',
  path: '/auth/role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bids': typeof BidsRouteWithChildren
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/my-posts': typeof MyPostsRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/search': typeof SearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/role': typeof AuthRoleRoute
  '/bids/$id': typeof BidsIdRoute
  '/onboarding/student': typeof OnboardingStudentRoute
  '/onboarding/tutor': typeof OnboardingTutorRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/requirements/$id': typeof RequirementsIdRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bids': typeof BidsRouteWithChildren
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/my-posts': typeof MyPostsRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/search': typeof SearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/role': typeof AuthRoleRoute
  '/bids/$id': typeof BidsIdRoute
  '/onboarding/student': typeof OnboardingStudentRoute
  '/onboarding/tutor': typeof OnboardingTutorRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/requirements/$id': typeof RequirementsIdRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bids': typeof BidsRouteWithChildren
  '/connections': typeof ConnectionsRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/my-posts': typeof MyPostsRoute
  '/profile': typeof ProfileRoute
  '/requests': typeof RequestsRoute
  '/search': typeof SearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/role': typeof AuthRoleRoute
  '/bids/$id': typeof BidsIdRoute
  '/onboarding/student': typeof OnboardingStudentRoute
  '/onboarding/tutor': typeof OnboardingTutorRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/requirements/$id': typeof RequirementsIdRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bids'
    | '/connections'
    | '/dashboard'
    | '/feed'
    | '/my-posts'
    | '/profile'
    | '/requests'
    | '/search'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/role'
    | '/bids/$id'
    | '/onboarding/student'
    | '/onboarding/tutor'
    | '/profiles/$id'
    | '/requirements/$id'
    | '/tutors/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bids'
    | '/connections'
    | '/dashboard'
    | '/feed'
    | '/my-posts'
    | '/profile'
    | '/requests'
    | '/search'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/role'
    | '/bids/$id'
    | '/onboarding/student'
    | '/onboarding/tutor'
    | '/profiles/$id'
    | '/requirements/$id'
    | '/tutors/$id'
  id:
    | '__root__'
    | '/'
    | '/bids'
    | '/connections'
    | '/dashboard'
    | '/feed'
    | '/my-posts'
    | '/profile'
    | '/requests'
    | '/search'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/role'
    | '/bids/$id'
    | '/onboarding/student'
    | '/onboarding/tutor'
    | '/profiles/$id'
    | '/requirements/$id'
    | '/tutors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BidsRoute: typeof BidsRouteWithChildren
  ConnectionsRoute: typeof ConnectionsRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  MyPostsRoute: typeof MyPostsRoute
  ProfileRoute: typeof ProfileRoute
  RequestsRoute: typeof RequestsRoute
  SearchRoute: typeof SearchRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRoleRoute: typeof AuthRoleRoute
  OnboardingStudentRoute: typeof OnboardingStudentRoute
  OnboardingTutorRoute: typeof OnboardingTutorRoute
  ProfilesIdRoute: typeof ProfilesIdRoute
  RequirementsIdRoute: typeof RequirementsIdRoute
  TutorsIdRoute: typeof TutorsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-posts': {
      id: '/my-posts'
      path: '/my-posts'
      fullPath: '/my-posts'
      preLoaderRoute: typeof MyPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors/$id': {
      id: '/tutors/$id'
      path: '/tutors/$id'
      fullPath: '/tutors/$id'
      preLoaderRoute: typeof TutorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements/$id': {
      id: '/requirements/$id'
      path: '/requirements/$id'
      fullPath: '/requirements/$id'
      preLoaderRoute: typeof RequirementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$id': {
      id: '/profiles/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof ProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/tutor': {
      id: '/onboarding/tutor'
      path: '/onboarding/tutor'
      fullPath: '/onboarding/tutor'
      preLoaderRoute: typeof OnboardingTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/student': {
      id: '/onboarding/student'
      path: '/onboarding/student'
      fullPath: '/onboarding/student'
      preLoaderRoute: typeof OnboardingStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids/$id': {
      id: '/bids/$id'
      path: '/$id'
      fullPath: '/bids/$id'
      preLoaderRoute: typeof BidsIdRouteImport
      parentRoute: typeof BidsRoute
    }
    '/auth/role': {
      id: '/auth/role'
      path: '/auth/role'
      fullPath: '/auth/role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BidsRouteChildren {
  BidsIdRoute: typeof BidsIdRoute
}

const BidsRouteChildren: BidsRouteChildren = {
  BidsIdRoute: BidsIdRoute,
}

const BidsRouteWithChildren = BidsRoute._addFileChildren(BidsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BidsRoute: BidsRouteWithChildren,
  ConnectionsRoute: ConnectionsRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  MyPostsRoute: MyPostsRoute,
  ProfileRoute: ProfileRoute,
  RequestsRoute: RequestsRoute,
  SearchRoute: SearchRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRoleRoute: AuthRoleRoute,
  OnboardingStudentRoute: OnboardingStudentRoute,
  OnboardingTutorRoute: OnboardingTutorRoute,
  ProfilesIdRoute: ProfilesIdRoute,
  RequirementsIdRoute: RequirementsIdRoute,
  TutorsIdRoute: TutorsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
